[package]
name = "bp35a1"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.8.0"
nom = { version = "7.1.3", default-features = false }
num_enum = { version = "0.7.3", default-features = false }
defmt = "0.3"